//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambiente
    {
        public int AmbienteID { get; set; }
        public Nullable<int> StockID { get; set; }
        public string Bathroom { get; set; }
        public string Bedromm { get; set; }
        public string Kitchen { get; set; }
        public string Living { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
