//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int UsuarioID { get; set; }
        public string Nombre_Completo { get; set; }
        public string Domicilio { get; set; }
        public Nullable<System.DateTime> Fecha_de_Nacimiento { get; set; }
        public string Mail { get; set; }
        public string Tipo_de_vivienda { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
